server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: message

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: